// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: creadorWebScanner.flex

package edu.cunoc.Nucleo;

import edu.cunoc.Enlace.Respuesta;import java_cup.runtime.*;import java.util.Date;


@SuppressWarnings("fallthrough")
public class CreadorWebLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\41\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200"+
    "\1\u3300\1\u3400\1\u1f00\1\u3500\1\u3600\1\u3700\1\u3800\1\u0100"+
    "\1\u3900\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u1f00"+
    "\1\u4000\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u1f00\1\u4c00\1\u4d00\1\u4e00"+
    "\1\u1f00\3\u0100\1\u4f00\1\u5000\1\u5100\12\u1f00\4\u0100\1\u5200"+
    "\17\u1f00\2\u0100\1\u5300\41\u1f00\2\u0100\1\u5400\1\u5500\2\u1f00"+
    "\1\u5600\1\u5700\27\u0100\1\u5800\2\u0100\1\u5900\45\u1f00\1\u0100"+
    "\1\u5a00\1\u5b00\11\u1f00\1\u5c00\27\u1f00\1\u5d00\1\u5e00\1\u5f00"+
    "\1\u6000\11\u1f00\1\u6100\1\u6200\5\u1f00\1\u6300\1\u6400\4\u1f00"+
    "\1\u6500\21\u1f00\246\u0100\1\u6600\20\u0100\1\u6700\1\u6800\25\u0100"+
    "\1\u6900\34\u0100\1\u6a00\14\u1f00\2\u0100\1\u6b00\u0e05\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\0\1\4\1\5\1\6\1\0\1\7\1\0\4\7"+
    "\1\0\1\10\1\7\1\11\1\12\1\13\2\14\6\15"+
    "\1\7\1\0\1\16\1\17\1\20\1\0\1\7\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\33"+
    "\1\51\1\52\1\1\1\53\1\0\1\54\1\0\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\1\33\1\64"+
    "\2\33\1\65\1\66\1\67\1\70\1\71\1\72\1\73"+
    "\1\74\1\75\1\76\1\77\4\33\1\0\1\100\55\0"+
    "\1\33\12\0\1\33\4\0\1\33\5\0\27\33\1\0"+
    "\37\33\1\0\u01ca\33\4\0\14\33\16\0\5\33\7\0"+
    "\1\33\1\0\1\33\201\0\5\33\1\0\2\33\2\0"+
    "\4\33\1\0\1\33\6\0\1\33\1\0\3\33\1\0"+
    "\1\33\1\0\24\33\1\0\123\33\1\0\213\33\10\0"+
    "\246\33\1\0\46\33\2\0\1\33\6\0\51\33\107\0"+
    "\33\33\4\0\4\33\55\0\53\33\25\0\12\33\4\0"+
    "\2\33\1\0\143\33\1\0\1\33\17\0\2\33\7\0"+
    "\17\33\2\0\1\33\20\0\1\33\1\0\36\33\35\0"+
    "\131\33\13\0\1\33\16\0\53\33\11\0\2\33\4\0"+
    "\1\33\5\0\26\33\4\0\1\33\11\0\1\33\3\0"+
    "\1\33\27\0\31\33\7\0\13\33\65\0\25\33\1\0"+
    "\10\33\106\0\66\33\3\0\1\33\22\0\1\33\7\0"+
    "\12\33\4\0\12\33\1\0\20\33\4\0\10\33\2\0"+
    "\2\33\2\0\26\33\1\0\7\33\1\0\1\33\3\0"+
    "\4\33\3\0\1\33\20\0\1\33\15\0\2\33\1\0"+
    "\3\33\4\0\14\33\12\0\1\33\10\0\6\33\4\0"+
    "\2\33\2\0\26\33\1\0\7\33\1\0\2\33\1\0"+
    "\2\33\1\0\2\33\37\0\4\33\1\0\1\33\7\0"+
    "\12\33\2\0\3\33\20\0\11\33\1\0\3\33\1\0"+
    "\26\33\1\0\7\33\1\0\2\33\1\0\5\33\3\0"+
    "\1\33\22\0\1\33\17\0\2\33\4\0\12\33\11\0"+
    "\1\33\13\0\10\33\2\0\2\33\2\0\26\33\1\0"+
    "\7\33\1\0\2\33\1\0\5\33\3\0\1\33\36\0"+
    "\2\33\1\0\3\33\4\0\12\33\1\0\1\33\21\0"+
    "\1\33\1\0\6\33\3\0\3\33\1\0\4\33\3\0"+
    "\2\33\1\0\1\33\1\0\2\33\3\0\2\33\3\0"+
    "\3\33\3\0\14\33\26\0\1\33\25\0\12\33\25\0"+
    "\10\33\1\0\3\33\1\0\27\33\1\0\20\33\3\0"+
    "\1\33\32\0\3\33\5\0\2\33\4\0\12\33\20\0"+
    "\1\33\4\0\10\33\1\0\3\33\1\0\27\33\1\0"+
    "\12\33\1\0\5\33\3\0\1\33\40\0\1\33\1\0"+
    "\2\33\4\0\12\33\1\0\2\33\22\0\10\33\1\0"+
    "\3\33\1\0\51\33\2\0\1\33\20\0\1\33\5\0"+
    "\3\33\10\0\3\33\4\0\12\33\12\0\6\33\5\0"+
    "\22\33\3\0\30\33\1\0\11\33\1\0\1\33\2\0"+
    "\7\33\37\0\12\33\21\0\60\33\1\0\2\33\14\0"+
    "\7\33\11\0\12\33\47\0\2\33\1\0\1\33\1\0"+
    "\5\33\1\0\30\33\1\0\1\33\1\0\12\33\1\0"+
    "\2\33\11\0\1\33\2\0\5\33\1\0\1\33\11\0"+
    "\12\33\2\0\4\33\40\0\1\33\37\0\12\33\26\0"+
    "\10\33\1\0\44\33\33\0\5\33\163\0\53\33\24\0"+
    "\13\33\6\0\6\33\4\0\4\33\3\0\1\33\3\0"+
    "\2\33\7\0\3\33\4\0\15\33\14\0\1\33\1\0"+
    "\12\33\6\0\46\33\1\0\1\33\5\0\1\33\2\0"+
    "\53\33\1\0\115\33\1\0\4\33\2\0\7\33\1\0"+
    "\1\33\1\0\4\33\2\0\51\33\1\0\4\33\2\0"+
    "\41\33\1\0\4\33\2\0\7\33\1\0\1\33\1\0"+
    "\4\33\2\0\17\33\1\0\71\33\1\0\4\33\2\0"+
    "\103\33\45\0\20\33\20\0\126\33\2\0\6\33\3\0"+
    "\u016c\33\2\0\21\33\1\0\32\33\5\0\113\33\6\0"+
    "\10\33\7\0\15\33\1\0\4\33\16\0\22\33\16\0"+
    "\22\33\16\0\15\33\1\0\3\33\17\0\64\33\43\0"+
    "\1\33\4\0\1\33\3\0\12\33\46\0\12\33\6\0"+
    "\131\33\7\0\5\33\2\0\42\33\1\0\1\33\5\0"+
    "\106\33\12\0\37\33\47\0\50\33\2\0\5\33\13\0"+
    "\54\33\4\0\32\33\6\0\12\33\46\0\27\33\11\0"+
    "\65\33\53\0\12\33\6\0\12\33\15\0\1\33\135\0"+
    "\57\33\21\0\7\33\4\0\12\33\51\0\36\33\15\0"+
    "\70\33\32\0\44\33\34\0\12\33\3\0\61\33\2\0"+
    "\11\33\7\0\53\33\2\0\3\33\51\0\4\33\1\0"+
    "\6\33\1\0\2\33\3\0\1\33\5\0\300\33\100\0"+
    "\26\33\2\0\6\33\2\0\46\33\2\0\6\33\2\0"+
    "\10\33\1\0\1\33\1\0\1\33\1\0\1\33\1\0"+
    "\37\33\2\0\65\33\1\0\7\33\1\0\1\33\3\0"+
    "\3\33\1\0\7\33\3\0\4\33\2\0\6\33\4\0"+
    "\15\33\5\0\3\33\1\0\7\33\164\0\1\33\15\0"+
    "\1\33\20\0\15\33\145\0\1\33\4\0\1\33\2\0"+
    "\12\33\1\0\1\33\3\0\5\33\6\0\1\33\1\0"+
    "\1\33\1\0\1\33\1\0\4\33\1\0\13\33\2\0"+
    "\4\33\5\0\5\33\4\0\1\33\64\0\2\33\u017b\0"+
    "\57\33\1\0\57\33\1\0\205\33\6\0\4\33\3\0"+
    "\2\33\14\0\46\33\1\0\1\33\5\0\1\33\2\0"+
    "\70\33\7\0\1\33\20\0\27\33\11\0\7\33\1\0"+
    "\7\33\1\0\7\33\1\0\7\33\1\0\7\33\1\0"+
    "\7\33\1\0\7\33\1\0\7\33\120\0\1\33\325\0"+
    "\2\33\52\0\5\33\5\0\2\33\4\0\126\33\6\0"+
    "\3\33\1\0\132\33\1\0\4\33\5\0\53\33\1\0"+
    "\136\33\21\0\33\33\65\0\306\33\112\0\360\33\20\0"+
    "\215\33\103\0\56\33\2\0\15\33\3\0\34\33\24\0"+
    "\57\33\20\0\37\33\2\0\106\33\61\0\11\33\2\0"+
    "\147\33\2\0\65\33\2\0\5\33\60\0\13\33\1\0"+
    "\3\33\1\0\4\33\1\0\27\33\35\0\64\33\16\0"+
    "\62\33\34\0\12\33\30\0\6\33\3\0\1\33\1\0"+
    "\2\33\1\0\46\33\12\0\27\33\31\0\35\33\7\0"+
    "\57\33\34\0\13\33\6\0\5\33\1\0\31\33\1\0"+
    "\51\33\27\0\3\33\1\0\10\33\4\0\12\33\6\0"+
    "\27\33\3\0\1\33\3\0\62\33\1\0\1\33\3\0"+
    "\2\33\2\0\5\33\2\0\1\33\1\0\1\33\30\0"+
    "\3\33\2\0\13\33\7\0\3\33\14\0\6\33\2\0"+
    "\6\33\2\0\6\33\11\0\7\33\1\0\7\33\1\0"+
    "\53\33\1\0\14\33\10\0\163\33\15\0\12\33\6\0"+
    "\244\33\14\0\27\33\4\0\61\33\4\0\156\33\2\0"+
    "\152\33\46\0\7\33\14\0\5\33\5\0\1\33\1\0"+
    "\12\33\1\0\15\33\1\0\5\33\1\0\1\33\1\0"+
    "\2\33\1\0\2\33\1\0\154\33\41\0\153\33\22\0"+
    "\100\33\2\0\66\33\50\0\14\33\164\0\5\33\1\0"+
    "\207\33\23\0\12\33\7\0\32\33\6\0\32\33\13\0"+
    "\131\33\3\0\6\33\2\0\6\33\2\0\6\33\2\0"+
    "\3\33\43\0\14\33\1\0\32\33\1\0\23\33\1\0"+
    "\2\33\1\0\17\33\2\0\16\33\42\0\173\33\205\0"+
    "\35\33\3\0\61\33\57\0\40\33\15\0\24\33\1\0"+
    "\10\33\6\0\46\33\12\0\36\33\2\0\44\33\4\0"+
    "\10\33\60\0\236\33\2\0\12\33\6\0\44\33\4\0"+
    "\44\33\4\0\50\33\10\0\64\33\234\0\67\33\11\0"+
    "\26\33\12\0\10\33\230\0\6\33\2\0\1\33\1\0"+
    "\54\33\1\0\2\33\3\0\1\33\2\0\27\33\12\0"+
    "\27\33\11\0\37\33\101\0\23\33\1\0\2\33\12\0"+
    "\26\33\12\0\32\33\106\0\70\33\6\0\2\33\100\0"+
    "\1\33\17\0\4\33\1\0\3\33\1\0\35\33\52\0"+
    "\35\33\3\0\35\33\43\0\10\33\1\0\34\33\33\0"+
    "\66\33\12\0\26\33\12\0\23\33\15\0\22\33\156\0"+
    "\111\33\67\0\63\33\15\0\63\33\15\0\44\33\14\0"+
    "\12\33\306\0\35\33\12\0\1\33\10\0\26\33\232\0"+
    "\27\33\14\0\65\33\56\0\12\33\23\0\55\33\40\0"+
    "\31\33\7\0\12\33\11\0\44\33\17\0\12\33\4\0"+
    "\1\33\13\0\43\33\3\0\1\33\14\0\60\33\16\0"+
    "\4\33\13\0\13\33\1\0\1\33\43\0\22\33\1\0"+
    "\31\33\124\0\7\33\1\0\1\33\1\0\4\33\1\0"+
    "\17\33\1\0\12\33\7\0\57\33\21\0\12\33\13\0"+
    "\10\33\2\0\2\33\2\0\26\33\1\0\7\33\1\0"+
    "\2\33\1\0\5\33\3\0\1\33\22\0\1\33\14\0"+
    "\5\33\236\0\65\33\22\0\4\33\5\0\12\33\5\0"+
    "\1\33\40\0\60\33\24\0\2\33\1\0\1\33\10\0"+
    "\12\33\246\0\57\33\51\0\4\33\44\0\60\33\24\0"+
    "\1\33\13\0\12\33\46\0\53\33\15\0\1\33\7\0"+
    "\12\33\66\0\33\33\25\0\12\33\306\0\54\33\164\0"+
    "\112\33\25\0\1\33\240\0\10\33\2\0\47\33\20\0"+
    "\1\33\1\0\1\33\34\0\1\33\12\0\50\33\7\0"+
    "\1\33\25\0\1\33\13\0\56\33\23\0\1\33\42\0"+
    "\71\33\7\0\11\33\1\0\45\33\21\0\1\33\17\0"+
    "\12\33\30\0\36\33\160\0\7\33\1\0\2\33\1\0"+
    "\46\33\25\0\1\33\11\0\12\33\6\0\6\33\1\0"+
    "\2\33\1\0\40\33\16\0\1\33\7\0\12\33\u0136\0"+
    "\23\33\15\0\232\33\346\0\304\33\274\0\57\33\321\0"+
    "\107\33\271\0\71\33\7\0\37\33\1\0\12\33\146\0"+
    "\36\33\22\0\60\33\20\0\4\33\14\0\12\33\11\0"+
    "\25\33\5\0\23\33\260\0\100\33\200\0\113\33\5\0"+
    "\1\33\102\0\15\33\100\0\2\33\1\0\1\33\34\0"+
    "\370\33\10\0\363\33\15\0\37\33\61\0\3\33\21\0"+
    "\4\33\10\0\u018c\33\4\0\153\33\5\0\15\33\3\0"+
    "\11\33\7\0\12\33\146\0\125\33\1\0\107\33\1\0"+
    "\2\33\2\0\1\33\2\0\2\33\2\0\4\33\1\0"+
    "\14\33\1\0\1\33\1\0\7\33\1\0\101\33\1\0"+
    "\4\33\2\0\10\33\1\0\7\33\1\0\34\33\1\0"+
    "\4\33\1\0\5\33\1\0\1\33\3\0\7\33\1\0"+
    "\u0154\33\2\0\31\33\1\0\31\33\1\0\37\33\1\0"+
    "\31\33\1\0\37\33\1\0\31\33\1\0\37\33\1\0"+
    "\31\33\1\0\37\33\1\0\31\33\1\0\10\33\2\0"+
    "\137\33\12\0\7\33\2\0\12\33\4\0\1\33\u0171\0"+
    "\54\33\4\0\12\33\6\0\305\33\73\0\104\33\7\0"+
    "\1\33\4\0\12\33\246\0\4\33\1\0\33\33\1\0"+
    "\2\33\1\0\1\33\2\0\1\33\1\0\12\33\1\0"+
    "\4\33\1\0\1\33\1\0\1\33\6\0\1\33\4\0"+
    "\1\33\1\0\1\33\1\0\1\33\1\0\3\33\1\0"+
    "\2\33\1\0\1\33\2\0\1\33\1\0\1\33\1\0"+
    "\1\33\1\0\1\33\1\0\1\33\1\0\2\33\1\0"+
    "\1\33\2\0\4\33\1\0\7\33\1\0\4\33\1\0"+
    "\4\33\1\0\1\33\1\0\12\33\1\0\21\33\5\0"+
    "\3\33\1\0\5\33\1\0\21\33\104\0\327\33\51\0"+
    "\65\33\13\0\336\33\2\0\u0182\33\16\0\u0131\33\37\0"+
    "\36\33\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27648];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\2\1\1\4\2\5\1\6"+
    "\1\7\1\10\20\1\1\11\1\12\3\1\1\2\1\1"+
    "\1\2\1\13\1\0\1\14\1\0\1\5\14\0\1\15"+
    "\26\0\1\5\36\0\1\16\3\0\1\5\20\0\1\17"+
    "\21\0\1\5\4\0\1\20\3\0\1\21\1\22\13\0"+
    "\1\23\3\0\1\24\1\25\2\0\1\26\1\27\3\0"+
    "\1\30\2\0\1\31\6\0\1\32\3\0\1\33\2\0"+
    "\1\34\1\35\2\0\1\36\2\0\1\37\6\0\1\40"+
    "\1\41\11\0\1\42\3\0\1\43\2\0\1\44\3\0"+
    "\1\45\15\0\1\46\3\0\1\47\2\0\1\50\4\0"+
    "\1\51\3\0\1\52\1\53\1\0\1\54\5\0\1\55"+
    "\3\0\1\56\26\0\1\57\5\0\1\60\13\0\1\61"+
    "\14\0\1\62\4\0\1\63\2\0\1\64\1\65\2\0"+
    "\1\66\3\0\1\67\1\70\4\0\1\71\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[356];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\101\0\101\0\202\0\101\0\303\0\u0104\0\101"+
    "\0\u0145\0\u0186\0\101\0\101\0\101\0\u01c7\0\u0208\0\u0249"+
    "\0\u028a\0\u02cb\0\u030c\0\u034d\0\u038e\0\u03cf\0\u0410\0\u0451"+
    "\0\u0492\0\u04d3\0\u0514\0\u0555\0\u0596\0\u05d7\0\101\0\u0618"+
    "\0\u0659\0\u069a\0\u06db\0\u071c\0\u075d\0\101\0\u079e\0\u0104"+
    "\0\u07df\0\u0820\0\u0861\0\u08a2\0\u08e3\0\u0924\0\u0965\0\u09a6"+
    "\0\u09e7\0\u0a28\0\u0a69\0\u0aaa\0\u0aeb\0\u0b2c\0\101\0\u0b6d"+
    "\0\u0bae\0\u0bef\0\u0c30\0\u0c71\0\u0cb2\0\u0cf3\0\u0d34\0\u0d75"+
    "\0\u0db6\0\u0df7\0\u0e38\0\u0e79\0\u0eba\0\u0efb\0\u0f3c\0\u0f7d"+
    "\0\u0fbe\0\u0fff\0\u1040\0\u1081\0\u10c2\0\u1103\0\u1144\0\u1185"+
    "\0\u11c6\0\u1207\0\u1248\0\u1289\0\u12ca\0\u130b\0\u134c\0\u138d"+
    "\0\u13ce\0\u140f\0\u1450\0\u1491\0\u14d2\0\u1513\0\u1554\0\u1595"+
    "\0\u15d6\0\u1617\0\u1658\0\u1699\0\u16da\0\u171b\0\u175c\0\u179d"+
    "\0\u17de\0\u181f\0\u1860\0\u18a1\0\101\0\u18e2\0\u1923\0\u1964"+
    "\0\u19a5\0\u19e6\0\u1a27\0\u1a68\0\u1aa9\0\u1aea\0\u1b2b\0\u1b6c"+
    "\0\u1bad\0\u1bee\0\u1c2f\0\u1c70\0\u1cb1\0\u1cf2\0\u1d33\0\u1d74"+
    "\0\u1db5\0\101\0\u1df6\0\u1e37\0\u1e78\0\u1eb9\0\u1efa\0\u1f3b"+
    "\0\u1f7c\0\u1fbd\0\u1ffe\0\u203f\0\u2080\0\u20c1\0\u2102\0\u2143"+
    "\0\u2184\0\u21c5\0\u2206\0\u2247\0\u2288\0\u22c9\0\u230a\0\u234b"+
    "\0\101\0\u238c\0\u23cd\0\u240e\0\101\0\101\0\u244f\0\u2490"+
    "\0\u24d1\0\u2512\0\u2553\0\u2594\0\u25d5\0\u2616\0\u2657\0\u2698"+
    "\0\u26d9\0\101\0\u271a\0\u275b\0\u279c\0\101\0\101\0\u27dd"+
    "\0\u281e\0\101\0\101\0\u285f\0\u28a0\0\u28e1\0\u2922\0\u2963"+
    "\0\u29a4\0\101\0\u29e5\0\u2a26\0\u2a67\0\u2aa8\0\u2ae9\0\u2b2a"+
    "\0\101\0\u2b6b\0\u2bac\0\u2bed\0\101\0\u2c2e\0\u2c6f\0\101"+
    "\0\101\0\u2cb0\0\u2cf1\0\101\0\u2d32\0\u2d73\0\101\0\u2db4"+
    "\0\u2df5\0\u2e36\0\u2e77\0\u2eb8\0\u2ef9\0\101\0\101\0\u2f3a"+
    "\0\u2f7b\0\u2fbc\0\u2ffd\0\u303e\0\u307f\0\u30c0\0\u3101\0\u3142"+
    "\0\101\0\u3183\0\u31c4\0\u3205\0\101\0\u3246\0\u3287\0\u32c8"+
    "\0\u3309\0\u334a\0\u338b\0\u33cc\0\u340d\0\u344e\0\u348f\0\u34d0"+
    "\0\u3511\0\u3552\0\u3593\0\u35d4\0\u3615\0\u3656\0\u3697\0\u36d8"+
    "\0\u3719\0\101\0\u375a\0\u379b\0\u37dc\0\101\0\u381d\0\u385e"+
    "\0\101\0\u389f\0\u38e0\0\u3921\0\u3962\0\u39a3\0\u39e4\0\u3a25"+
    "\0\u3a66\0\101\0\101\0\u3aa7\0\101\0\u3ae8\0\u3b29\0\u3b6a"+
    "\0\u3bab\0\u3bec\0\101\0\u3c2d\0\u3c6e\0\u3caf\0\101\0\u3cf0"+
    "\0\u3d31\0\u3d72\0\u3db3\0\u3df4\0\u3e35\0\u3e76\0\u3eb7\0\u3ef8"+
    "\0\u3f39\0\u3f7a\0\u3fbb\0\u3ffc\0\u403d\0\u407e\0\u40bf\0\u4100"+
    "\0\u4141\0\u4182\0\u41c3\0\u4204\0\u4245\0\101\0\u4286\0\u42c7"+
    "\0\u4308\0\u4349\0\u438a\0\101\0\u43cb\0\u440c\0\u444d\0\u448e"+
    "\0\u44cf\0\u4510\0\u4551\0\u4592\0\u45d3\0\u4614\0\u4655\0\101"+
    "\0\u4696\0\u46d7\0\u4718\0\u4759\0\u479a\0\u47db\0\u481c\0\u485d"+
    "\0\u489e\0\u48df\0\u4920\0\u4961\0\101\0\u49a2\0\u49e3\0\u4a24"+
    "\0\u4a65\0\101\0\u4aa6\0\u4ae7\0\101\0\101\0\u4b28\0\u4b69"+
    "\0\101\0\u4baa\0\u4beb\0\u4c2c\0\101\0\101\0\u4c6d\0\u4cae"+
    "\0\u4cef\0\u4d30\0\101\0\101";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[356];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\2\1\7"+
    "\1\10\1\11\3\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\2\2\1\24\1\25\2\2"+
    "\1\26\1\27\1\30\1\31\2\2\1\32\1\33\1\34"+
    "\1\35\3\2\1\36\1\37\1\7\1\40\3\2\1\22"+
    "\1\3\1\2\1\41\1\2\1\42\1\43\1\2\1\44"+
    "\1\2\1\3\1\2\1\45\1\2\1\35\1\46\103\0"+
    "\1\3\110\0\4\47\3\0\6\47\26\0\6\47\24\0"+
    "\1\50\1\0\1\50\1\0\4\50\3\0\31\50\2\0"+
    "\24\50\13\0\4\51\75\0\4\52\106\0\1\53\3\0"+
    "\1\54\4\0\1\55\1\0\1\56\5\0\1\57\12\0"+
    "\1\53\15\0\1\57\42\0\1\60\66\0\1\61\6\0"+
    "\1\62\2\0\1\63\66\0\1\64\117\0\1\65\30\0"+
    "\1\65\30\0\1\66\77\0\1\67\10\0\1\70\13\0"+
    "\1\71\14\0\1\70\57\0\1\72\60\0\1\73\11\0"+
    "\1\74\21\0\1\73\56\0\1\75\5\0\1\76\22\0"+
    "\1\75\52\0\1\77\57\0\1\100\33\0\1\101\54\0"+
    "\1\102\74\0\1\103\3\0\1\104\32\0\1\104\57\0"+
    "\1\105\56\0\1\106\7\0\1\107\23\0\1\106\6\0"+
    "\1\107\15\0\3\110\1\0\1\111\1\0\7\111\3\0"+
    "\31\111\1\112\1\0\6\111\1\113\4\111\1\113\3\111"+
    "\1\113\1\111\1\113\2\111\24\0\1\53\20\0\1\57"+
    "\12\0\1\53\15\0\1\57\40\0\1\70\30\0\1\70"+
    "\37\0\1\73\33\0\1\73\56\0\1\75\30\0\1\75"+
    "\31\0\1\101\33\0\1\101\54\0\1\104\32\0\1\104"+
    "\26\0\4\114\3\0\6\114\26\0\6\114\30\0\4\115"+
    "\75\0\4\116\106\0\1\117\33\0\1\117\63\0\1\120"+
    "\67\0\1\121\12\0\1\122\57\0\1\123\117\0\1\124"+
    "\30\0\1\124\47\0\1\125\74\0\1\126\63\0\1\127"+
    "\113\0\1\130\106\0\1\131\67\0\1\132\32\0\1\132"+
    "\37\0\1\133\76\0\1\134\33\0\1\134\64\0\1\135"+
    "\102\0\1\136\73\0\1\137\30\0\1\137\35\0\1\140"+
    "\111\0\1\141\30\0\1\141\37\0\1\142\104\0\1\143"+
    "\73\0\1\144\2\0\1\145\12\0\1\146\30\0\1\146"+
    "\47\0\1\146\30\0\1\146\51\0\1\147\104\0\1\150"+
    "\74\0\1\151\30\0\1\151\50\0\1\152\67\0\1\153"+
    "\30\0\1\153\37\0\1\154\33\0\1\154\21\0\3\110"+
    "\46\0\1\112\7\0\1\110\4\0\1\110\3\0\1\110"+
    "\1\0\1\110\10\0\1\111\1\0\7\111\3\0\31\111"+
    "\1\0\1\155\24\111\6\0\1\156\1\0\7\156\3\0"+
    "\31\156\2\0\24\156\2\0\3\110\1\0\1\111\1\0"+
    "\7\111\3\0\31\111\1\112\1\155\6\111\1\113\4\111"+
    "\1\113\3\111\1\113\1\111\1\113\2\111\13\0\4\157"+
    "\3\0\6\157\26\0\6\157\30\0\4\160\75\0\4\161"+
    "\114\0\1\162\32\0\1\162\41\0\1\163\111\0\1\164"+
    "\107\0\1\165\63\0\1\166\101\0\1\167\32\0\1\167"+
    "\56\0\1\170\102\0\1\171\77\0\1\172\74\0\1\173"+
    "\66\0\1\174\114\0\1\175\30\0\1\175\36\0\1\176"+
    "\77\0\1\177\33\0\1\177\62\0\1\200\77\0\1\201"+
    "\101\0\1\202\30\0\1\202\33\0\1\203\71\0\1\204"+
    "\33\0\1\204\70\0\1\205\61\0\1\206\113\0\1\207"+
    "\67\0\1\210\70\0\1\211\20\0\1\212\12\0\1\211"+
    "\15\0\1\212\36\0\1\213\113\0\1\214\101\0\1\215"+
    "\30\0\1\215\23\0\1\216\116\0\1\217\30\0\1\217"+
    "\35\0\1\220\33\0\1\220\24\0\1\156\1\0\7\156"+
    "\3\0\31\156\1\0\1\221\24\156\13\0\4\222\3\0"+
    "\6\222\26\0\6\222\26\0\1\223\100\0\1\223\1\0"+
    "\4\224\122\0\1\225\30\0\1\225\37\0\1\226\76\0"+
    "\1\227\115\0\1\230\75\0\1\231\63\0\1\232\33\0"+
    "\1\232\43\0\1\233\121\0\1\234\63\0\1\235\115\0"+
    "\1\236\61\0\1\237\122\0\1\240\30\0\1\240\23\0"+
    "\1\241\104\0\1\242\33\0\1\242\50\0\1\243\100\0"+
    "\1\244\75\0\1\245\114\0\1\246\30\0\1\246\26\0"+
    "\1\247\15\0\1\250\66\0\1\251\100\0\1\252\111\0"+
    "\1\253\77\0\1\254\30\0\1\254\33\0\1\255\33\0"+
    "\1\255\62\0\1\256\100\0\1\257\75\0\1\260\30\0"+
    "\1\260\55\0\1\261\100\0\1\262\30\0\1\262\44\0"+
    "\1\263\30\0\1\263\11\0\3\264\56\0\1\264\4\0"+
    "\1\264\3\0\1\264\1\0\1\264\15\0\4\265\3\0"+
    "\6\265\26\0\6\265\30\0\2\266\77\0\4\224\121\0"+
    "\1\267\30\0\1\267\32\0\1\270\100\0\1\271\100\0"+
    "\1\272\124\0\1\273\30\0\1\273\44\0\1\274\57\0"+
    "\1\275\107\0\1\276\75\0\1\277\33\0\1\277\73\0"+
    "\1\300\62\0\1\301\30\0\1\301\36\0\1\302\101\0"+
    "\1\303\103\0\1\304\74\0\1\305\33\0\1\305\73\0"+
    "\1\306\100\0\1\307\62\0\1\310\63\0\1\311\104\0"+
    "\1\312\33\0\1\312\45\0\1\313\33\0\1\313\55\0"+
    "\1\314\30\0\1\314\41\0\1\315\50\0\3\264\46\0"+
    "\1\316\7\0\1\264\4\0\1\264\3\0\1\264\1\0"+
    "\1\264\15\0\4\317\3\0\6\317\26\0\6\317\30\0"+
    "\4\320\110\0\1\321\33\0\1\321\61\0\1\322\61\0"+
    "\1\323\121\0\1\324\30\0\1\324\57\0\1\325\66\0"+
    "\1\326\57\0\1\327\123\0\1\330\30\0\1\330\26\0"+
    "\1\331\11\0\1\332\105\0\1\333\67\0\1\334\72\0"+
    "\1\335\115\0\1\336\103\0\1\337\101\0\1\340\30\0"+
    "\1\340\42\0\1\341\30\0\1\341\47\0\1\342\46\0"+
    "\1\343\1\0\7\343\3\0\31\343\2\0\24\343\11\0"+
    "\1\344\133\0\1\345\30\0\1\345\60\0\1\346\55\0"+
    "\1\347\106\0\1\350\30\0\1\350\33\0\1\351\14\0"+
    "\1\352\2\0\1\353\56\0\1\354\33\0\1\354\65\0"+
    "\1\355\75\0\1\356\65\0\1\357\77\0\1\360\76\0"+
    "\1\361\100\0\1\362\110\0\1\363\111\0\1\364\30\0"+
    "\1\364\61\0\1\365\31\0\1\343\1\0\7\343\3\0"+
    "\31\343\1\0\1\366\24\343\13\0\3\367\107\0\1\370"+
    "\114\0\1\371\104\0\1\372\30\0\1\372\43\0\1\373"+
    "\62\0\1\374\110\0\1\375\112\0\1\376\30\0\1\376"+
    "\31\0\1\377\77\0\1\u0100\75\0\1\u0101\100\0\1\u0102"+
    "\121\0\1\u0103\65\0\1\u0104\115\0\1\u0105\73\0\1\u0106"+
    "\30\0\1\u0106\33\0\1\u0107\11\0\1\u0108\44\0\3\u0109"+
    "\46\0\1\112\1\u010a\6\0\1\u0109\4\0\1\u0109\3\0"+
    "\1\u0109\1\0\1\u0109\15\0\4\u010b\122\0\1\u010c\77\0"+
    "\1\u010d\77\0\1\u010e\72\0\1\u010f\115\0\1\u0110\55\0"+
    "\1\u0111\110\0\1\u0112\111\0\1\u0113\112\0\1\u0114\55\0"+
    "\1\u0115\100\0\1\u0116\112\0\1\u0117\30\0\1\u0117\46\0"+
    "\1\u0118\75\0\1\u0119\42\0\3\u0109\46\0\1\316\1\u010a"+
    "\6\0\1\u0109\4\0\1\u0109\3\0\1\u0109\1\0\1\u0109"+
    "\40\0\1\u011a\103\0\1\u011b\71\0\1\u011c\100\0\1\u011d"+
    "\72\0\1\u011e\103\0\1\u011f\75\0\1\u0120\14\0\1\u0121"+
    "\76\0\1\u0122\101\0\1\u0123\66\0\1\u0124\77\0\1\u0125"+
    "\114\0\1\u0126\77\0\1\u0127\77\0\1\u0128\101\0\1\u0129"+
    "\72\0\1\u012a\100\0\1\u012b\106\0\1\u012c\62\0\1\u012d"+
    "\100\0\1\u012e\133\0\1\u012f\45\0\1\u0130\110\0\1\u0131"+
    "\106\0\1\u0132\77\0\1\u0133\63\0\1\u0134\133\0\1\u0135"+
    "\63\0\1\u0136\64\0\1\u0137\112\0\1\u0138\72\0\1\u0139"+
    "\120\0\1\u013a\54\0\1\u013b\103\0\1\u013c\110\0\1\u013d"+
    "\67\0\1\u013e\122\0\1\u013f\67\0\1\u0140\63\0\1\u0141"+
    "\117\0\1\u0142\71\0\1\u0143\74\0\1\u0144\104\0\1\u0145"+
    "\100\0\1\u0146\74\0\1\u0147\111\0\1\u0148\67\0\1\u0149"+
    "\76\0\1\u014a\114\0\1\u014b\77\0\1\u014c\64\0\1\u014d"+
    "\115\0\1\u014e\64\0\1\u014f\113\0\1\u0150\106\0\1\u0151"+
    "\56\0\1\u0152\107\0\1\u0153\105\0\1\u0154\63\0\1\u0155"+
    "\115\0\1\u0156\63\0\1\u0157\123\0\1\u0158\61\0\1\u0159"+
    "\112\0\1\u015a\66\0\1\u015b\76\0\1\u015c\102\0\1\u015d"+
    "\111\0\1\u015e\100\0\1\u015f\73\0\1\u0160\113\0\1\u0161"+
    "\73\0\1\u0162\66\0\1\u0163\111\0\1\u0164\42\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[19825];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\2\1\1\11\2\1\3\11"+
    "\21\1\1\11\6\1\1\11\1\0\1\1\1\0\1\1"+
    "\14\0\1\11\26\0\1\1\36\0\1\11\3\0\1\1"+
    "\20\0\1\11\21\0\1\1\4\0\1\11\3\0\2\11"+
    "\13\0\1\11\3\0\2\11\2\0\2\11\3\0\1\1"+
    "\2\0\1\11\6\0\1\11\3\0\1\11\2\0\2\11"+
    "\2\0\1\11\2\0\1\11\6\0\2\11\11\0\1\11"+
    "\3\0\1\11\2\0\1\1\3\0\1\1\15\0\1\11"+
    "\3\0\1\11\2\0\1\11\4\0\1\1\3\0\2\11"+
    "\1\0\1\11\5\0\1\11\3\0\1\11\26\0\1\11"+
    "\5\0\1\11\13\0\1\11\14\0\1\11\4\0\1\11"+
    "\2\0\2\11\2\0\1\11\3\0\2\11\4\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[356];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

    private Respuesta respuesta;


       private Symbol symbol(int type) {
           return new Symbol(type, yyline+1, yycolumn+1);
       }

        private Symbol symbol(int type, Object value) {
            return new Symbol(type, yyline+1, yycolumn+1, value);
        }

        private void error(String message) {
           if (respuesta==null){
               respuesta = new Respuesta();
           }
           respuesta.addErrorLexico("Error lexico en linea "+(yyline+1)+", columna "+(yycolumn+1)+" : "+message);
            System.out.println("Error lexico en linea "+(yyline+1)+", columna "+(yycolumn+1)+" : "+message);
        }

        public Respuesta getRespuesta(){
           return respuesta;
        }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CreadorWebLexer(java.io.Reader in) {
    this.zzReader = in;
    this.respuesta = new Respuesta();
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { error("Simbolo invalido <"+yytext()+"> en linea "+(yyline+1)+" en columna "+ (yycolumn+1));
            }
          // fall through
          case 59: break;
          case 2:
            { 
            }
          // fall through
          case 60: break;
          case 3:
            { return symbol(sym.COMILLA);
            }
          // fall through
          case 61: break;
          case 4:
            { return symbol(sym.DIAGONAL);
            }
          // fall through
          case 62: break;
          case 5:
            { return symbol(sym.ENTERO, new Integer(yytext()));
            }
          // fall through
          case 63: break;
          case 6:
            { return symbol(sym.MENOSQUE);
            }
          // fall through
          case 64: break;
          case 7:
            { return symbol(sym.IGUAL);
            }
          // fall through
          case 65: break;
          case 8:
            { return symbol(sym.MAYORQUE);
            }
          // fall through
          case 66: break;
          case 9:
            { return symbol(sym.COR_OP);
            }
          // fall through
          case 67: break;
          case 10:
            { return symbol(sym.COR_CLO);
            }
          // fall through
          case 68: break;
          case 11:
            { return symbol(sym.BARRA);
            }
          // fall through
          case 69: break;
          case 12:
            { return symbol(sym.ID, new String(yytext()));
            }
          // fall through
          case 70: break;
          case 13:
            { return symbol(sym.PAR_ID);
            }
          // fall through
          case 71: break;
          case 14:
            { return symbol(sym.MULTI, new String(yytext()));
            }
          // fall through
          case 72: break;
          case 15:
            { return symbol(sym.MENU);
            }
          // fall through
          case 73: break;
          case 16:
            { return symbol(sym.ANCHO);
            }
          // fall through
          case 74: break;
          case 17:
            { return symbol(sym.CLASE);
            }
          // fall through
          case 75: break;
          case 18:
            { return symbol(sym.COLOR);
            }
          // fall through
          case 76: break;
          case 19:
            { return symbol(sym.PADRE);
            }
          // fall through
          case 77: break;
          case 20:
            { return symbol(sym.SITIO);
            }
          // fall through
          case 78: break;
          case 21:
            { return symbol(sym.TEXTO);
            }
          // fall through
          case 79: break;
          case 22:
            { return symbol(sym.VALOR);
            }
          // fall through
          case 80: break;
          case 23:
            { return symbol(sym.VIDEO);
            }
          // fall through
          case 81: break;
          case 24:
            { return symbol(sym.ACCION);
            }
          // fall through
          case 82: break;
          case 25:
            { return symbol(sym.ALTURA);
            }
          // fall through
          case 83: break;
          case 26:
            { return symbol(sym.IMAGEN);
            }
          // fall through
          case 84: break;
          case 27:
            { return symbol(sym.NOMBRE);
            }
          // fall through
          case 85: break;
          case 28:
            { return symbol(sym.ORIGEN);
            }
          // fall through
          case 86: break;
          case 29:
            { return symbol(sym.PAGINA);
            }
          // fall through
          case 87: break;
          case 30:
            { return symbol(sym.TITULO_CLASS);
            }
          // fall through
          case 88: break;
          case 31:
            { return symbol(sym.HEXA, new String(yytext()));
            }
          // fall through
          case 89: break;
          case 32:
            { return symbol(sym.CENTRAR);
            }
          // fall through
          case 90: break;
          case 33:
            { return symbol(sym.DERECHA);
            }
          // fall through
          case 91: break;
          case 34:
            { return symbol(sym.PARRAFO);
            }
          // fall through
          case 92: break;
          case 35:
            { return symbol(sym.ACCIONES);
            }
          // fall through
          case 93: break;
          case 36:
            { return symbol(sym.ATRIBUTO);
            }
          // fall through
          case 94: break;
          case 37:
            { return symbol(sym.ETIQUETA);
            }
          // fall through
          case 95: break;
          case 38:
            { return symbol(sym.ATRIBUTOS);
            }
          // fall through
          case 96: break;
          case 39:
            { return symbol(sym.ETIQUETAS_XML);
            }
          // fall through
          case 97: break;
          case 40:
            { return symbol(sym.IZQUIERDA);
            }
          // fall through
          case 98: break;
          case 41:
            { return symbol(sym.PARAMETRO);
            }
          // fall through
          case 99: break;
          case 42:
            { return symbol(sym.OTRO, new String(yytext()));
            }
          // fall through
          case 100: break;
          case 43:
            { return symbol(sym.FECHA, new String(yytext()));
            }
          // fall through
          case 101: break;
          case 44:
            { return symbol(sym.ALINEACION);
            }
          // fall through
          case 102: break;
          case 45:
            { return symbol(sym.JUSTIFICAR);
            }
          // fall through
          case 103: break;
          case 46:
            { return symbol(sym.PARAMETROS);
            }
          // fall through
          case 104: break;
          case 47:
            { return symbol(sym.NUEVA_PAG);
            }
          // fall through
          case 105: break;
          case 48:
            { return symbol(sym.DEL_PAG);
            }
          // fall through
          case 106: break;
          case 49:
            { return symbol(sym.DATE_CREACION);
            }
          // fall through
          case 107: break;
          case 50:
            { return symbol(sym.NUEVA_WEB);
            }
          // fall through
          case 108: break;
          case 51:
            { return symbol(sym.DEL_WEB);
            }
          // fall through
          case 109: break;
          case 52:
            { return symbol(sym.MOD_PAG);
            }
          // fall through
          case 110: break;
          case 53:
            { return symbol(sym.USER_CREACION);
            }
          // fall through
          case 111: break;
          case 54:
            { return symbol(sym.DEL_COMP);
            }
          // fall through
          case 112: break;
          case 55:
            { return symbol(sym.ADD_COMP);
            }
          // fall through
          case 113: break;
          case 56:
            { return symbol(sym.DATE_MOD);
            }
          // fall through
          case 114: break;
          case 57:
            { return symbol(sym.MOD_COMP);
            }
          // fall through
          case 115: break;
          case 58:
            { return symbol(sym.USER_MOD);
            }
          // fall through
          case 116: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
