
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.cunoc.Nucleo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIAGONAL = 33;
  public static final int ALINEACION = 21;
  public static final int PAGINA = 18;
  public static final int PARAMETROS = 40;
  public static final int MENOSQUE = 30;
  public static final int COR_CLO = 35;
  public static final int DEL_COMP = 8;
  public static final int OTRO = 55;
  public static final int MOD_PAG = 6;
  public static final int NOMBRE = 37;
  public static final int ENTERO = 57;
  public static final int ANCHO = 25;
  public static final int HEXA = 53;
  public static final int IZQUIERDA = 27;
  public static final int VIDEO = 49;
  public static final int FECHA = 58;
  public static final int MENU = 46;
  public static final int MAYORQUE = 31;
  public static final int IGUAL = 32;
  public static final int CENTRAR = 26;
  public static final int TITULO_CLASS = 52;
  public static final int NUEVA_WEB = 3;
  public static final int TITULO = 15;
  public static final int PADRE = 17;
  public static final int NUEVA_PAG = 2;
  public static final int ID = 54;
  public static final int EOF = 0;
  public static final int CLASE = 19;
  public static final int COMILLA = 45;
  public static final int error = 1;
  public static final int DATE_MOD = 13;
  public static final int ATRIBUTOS = 38;
  public static final int USER_MOD = 14;
  public static final int PAR_ID = 10;
  public static final int ATRIBUTO = 39;
  public static final int ACCION = 36;
  public static final int USER_CREACION = 11;
  public static final int COLOR = 22;
  public static final int BARRA = 50;
  public static final int VALOR = 51;
  public static final int DEL_WEB = 4;
  public static final int MOD_COMP = 9;
  public static final int ADD_COMP = 7;
  public static final int IMAGEN = 48;
  public static final int DERECHA = 28;
  public static final int PARRAFO = 47;
  public static final int ORIGEN = 23;
  public static final int DEL_PAG = 5;
  public static final int MULTI = 56;
  public static final int ACCIONES = 44;
  public static final int ETIQUETAS_XML = 42;
  public static final int PARAMETRO = 41;
  public static final int SITIO = 16;
  public static final int DATE_CREACION = 12;
  public static final int TEXTO = 20;
  public static final int ETIQUETA = 43;
  public static final int JUSTIFICAR = 29;
  public static final int ALTURA = 24;
  public static final int COR_OP = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUEVA_PAG",
  "NUEVA_WEB",
  "DEL_WEB",
  "DEL_PAG",
  "MOD_PAG",
  "ADD_COMP",
  "DEL_COMP",
  "MOD_COMP",
  "PAR_ID",
  "USER_CREACION",
  "DATE_CREACION",
  "DATE_MOD",
  "USER_MOD",
  "TITULO",
  "SITIO",
  "PADRE",
  "PAGINA",
  "CLASE",
  "TEXTO",
  "ALINEACION",
  "COLOR",
  "ORIGEN",
  "ALTURA",
  "ANCHO",
  "CENTRAR",
  "IZQUIERDA",
  "DERECHA",
  "JUSTIFICAR",
  "MENOSQUE",
  "MAYORQUE",
  "IGUAL",
  "DIAGONAL",
  "COR_OP",
  "COR_CLO",
  "ACCION",
  "NOMBRE",
  "ATRIBUTOS",
  "ATRIBUTO",
  "PARAMETROS",
  "PARAMETRO",
  "ETIQUETAS_XML",
  "ETIQUETA",
  "ACCIONES",
  "COMILLA",
  "MENU",
  "PARRAFO",
  "IMAGEN",
  "VIDEO",
  "BARRA",
  "VALOR",
  "TITULO_CLASS",
  "HEXA",
  "ID",
  "OTRO",
  "MULTI",
  "ENTERO",
  "FECHA"
  };
}

